name: flutter_portfolio
description: Portfolio-app kawaii pastel de Marilu
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  fl_chart: ^1.1.1
  csv: ^6.0.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  open_filex: ^4.5.0
  shared_preferences: ^2.3.2
  flutter_web_plugins:
    sdk: flutter
  pdf: ^3.10.7
  printing: ^5.13.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  # Habilita los iconos y estilos base de Material
  uses-material-design: true
  # Directorios de assets estáticos incluidos en el build web
  assets:
    - assets/data/
    - assets/img/
    - assets/images/

# Splash screen kawaii para Android/iOS
flutter_native_splash:
  color: "#FFF9E8"
  image: assets/img/raton_menu.png
  android: true
  ios: true
  color_dark: "#1f1b16"
  image_dark: assets/img/raton_menu.png
  android_12:
    color: "#FFF9E8"
    image: assets/img/raton_menu.png
